name: Notify Discord on Develop Update

on:
  push:
    branches:
      - develop

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop')
    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '@everyone, the develop branch has been updated. Pull the latest changes!'
